env {
  parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  StarRocks {
    nodeUrls = ["starrocks:8030"]  # 读取 starrocks (172.16.0.10)
    username = "root"
    password = ""
    database = "test"
    table_list = [
        {
            table = "user"
            scan_filter = "age > 25"
            schema = {
                columns = [
                    {
                        name = id
                        type = bigint
                        nullable = false
                    },{
                        name = name
                        type = string
                    },{
                        name = age
                        type = int
                    }
                ]
                primaryKey = {
                    name = "id"
                    columnNames = [id]
                }
            }
        },
        {
            table = "info"
            scan_filter = "age > 25"
            schema = {
                columns = [
                    {
                        name = id
                        type = bigint
                        nullable = false
                    },{
                        name = sex
                        type = string
                    },{
                        name = age
                        type = int
                    }
                ]
                primaryKey = {
                    name = "id"
                    columnNames = [id]
                }
            }
        }
    ]

  }
}

sink {
  StarRocks {
    nodeUrls = ["starrocks1:8030"] # 写入 starrocks1 (172.16.0.11)
    base-url = "jdbc:mysql://starrocks1:9030/"
    username = "root"
    password = ""
    database = "test"
    batch_max_rows = 10000
    labelPrefix = "sr_to_sr_sync"
  }
}
