env {
  parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  StarRocks {
    nodeUrls = ["172.17.64.175:8030"]
    username = "rixiang"
    password = "6U1N6vuL2v&DWsl"
    database = "dws"
    table = "dws_user_tag_temp"
    schema = {
        columns = [
            {
                name = user_id
                type = bigint
            },{
                name = tag_id
                type = bigint
            },{
                name = tag_value
                type = string
            }
        ]
    }
  }
}

sink {
  StarRocks {
    nodeUrls = ["172.16.0.10:8030"]
    base-url = "jdbc:mysql://172.16.0.10:9030/"
    username = "root"
    password = ""
    database = "test"
    table = "dws_user_tag_temp"
    batch_max_rows = 10000
    labelPrefix = "sr_to_sr_sync"
  }
}
